# Generated by Django 6.1.1 on 2026-09-30 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Worksheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("exam_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="e.g. SPM 2023, UPSR trial, Kumon level D",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worksheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worksheets",
                        to="curriculum.subject",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worksheets",
                        to="curriculum.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "topic", "title"],
            },
        ),
        migrations.CreateModel(
            name="AnswerSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_key", models.CharField(max_length=500)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Marking scheme notes fed to the auto-grader",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "worksheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_sheets",
                        to="worksheets.worksheet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorksheetPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "image_key",
                    models.CharField(
                        help_text="Object-storage key of the rendered page image",
                        max_length=500,
                    ),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "answer_regions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional [{x, y, w, h, label}] boxes marking where answers go. Not required — students may write anywhere — but improves auto-grading when present.",
                    ),
                ),
                (
                    "worksheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="worksheets.worksheet",
                    ),
                ),
            ],
            options={
                "ordering": ["worksheet", "order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("worksheet", "order"),
                        name="unique_page_order_per_worksheet",
                    )
                ],
            },
        ),
    ]
